fix path on unit test and removing properties from build.gradle (#48)
* fix path on unit test and removing properties from build.gradle

* adding stacktrace to test task to determinate where the problem is

* Fixing the unit test when generate driven adapters and validate structure tasks, and separting in the pipeline the gradle test jacocoTestReport value and the copy file to root project task

* increasing code coverage

* increasing coverage on driven adapters models

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -23,7 +23,9 @@ jobs:
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
       - name: Execute jacocoTestReport
-        run: ./gradlew test jacocoTestReport && cp build/reports/jacoco/report.xml jacoco.xml || echo "Code coverage failed"
+        run: ./gradlew test jacocoTestReport
+      - name: copy the reportTest to codeCoverage
+        run: cp build/reports/jacoco/report.xml jacoco.xml || echo "Code coverage failed"
       - name: Build with Gradle
         run: ./gradlew build --refresh-dependencies --no-daemon --continue
       - name: Push codeCoverage to Codecov
